### ISSUE TITLE
using with minitest

### ISSUE THREAD

**Issue by sandrods** [goodwill/capybara-select2#29]
Hi, 

I'm trying to use capybara-select with `minitest-rails-capybara` with no success.

Could you point me into the direction on how to configure capybara-select2 to be included into minitest?

TIA

**Comment by kgathi2** [comment]
```
#ruby
class ActiveSupport::TestCase
include Capybara::Select2
  include Capybara::Selectors::TagSelector
end

```

**Comment by vestedpr-dev** [comment]
For me it was the following:

```
class Capybara::Rails::TestCase
  include CapybaraSelect2
end
```
