### ISSUE TITLE
Release the 1.0.0 gem

### ISSUE THREAD

**Issue by p8** [goodwill/capybara-select2#33]
The current rubygems gem is versioned at 0.0.8 but master has lots of fixes and is versioned at 1.0.0.

**Comment by rposborne** [comment]
:+1:

**Comment by divineforest** [comment]
@goodwill please :)

**Comment by wvengen** [comment]
Please?

**Comment by goodwill** [comment]
Done.

Regards,

William Yeung

Tofugear Limited

E: william@tofugear.com
T: +852 21519830
M: +852 92538475
W: http://tofugear.com

**Comment by p8** [comment]
Thanks!

**Comment by wvengen** [comment]
Thank you!
